[build]
builder = "nixpacks"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"

# Backend service configuration
[[services]]
name = "backend"
internal_port = 3000
healthcheck_path = "/"
envs = [
  "DATABASE_URL",
  "JWT_SECRET",
  "CORS_ORIGIN",
  "PORT=3000"
]

# Frontend service configuration
[[services]]
name = "frontend"
internal_port = 5173
healthcheck_path = "/"
envs = [
  "VITE_API_URL",
  "PORT=5173"
]