[build]
builder = "nixpacks"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"

[[services]]
name = "backend"
dockerfile = "./backend/Dockerfile"
internal_port = 3000
envs = [
  "DATABASE_URL",
  "JWT_SECRET",
  "CORS_ORIGIN"
]

[[services]]
name = "frontend"
dockerfile = "./frontend/Dockerfile"
internal_port = 5173
envs = [
  "VITE_API_URL"
]