[build]
builder = "nixpacks"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"

# Service specific configurations
[[services]]
internal_port = 3000
envs = [
  "DATABASE_URL",
  "JWT_SECRET",
  "CORS_ORIGIN",
  "PORT"
]

[[services]]
internal_port = 5173
envs = [
  "VITE_API_URL",
  "PORT"
]